using System.Collections.Concurrent;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Reflection;
using MonitoringDemo.ApiService.Telemetry;

namespace MonitoringDemo.ApiService.Services;

public sealed class OpenTelemetryLabService
{
    private const int MaximumSamples = 5_000;
    private static readonly string[] Operations = ["checkout", "catalog", "payment", "fulfillment"];
    private static readonly string[] Methods = ["GET", "POST", "POST", "PUT"];

    private readonly AppActivitySource _activitySource;
    private readonly ILogger<OpenTelemetryLabService> _logger;
    private readonly Counter<long> _requestCounter;
    private readonly Histogram<double> _durationHistogram;
    private readonly ConcurrentQueue<OpenTelemetrySample> _samples = new();
    private readonly IReadOnlyList<TelemetryResourceAttribute> _resourceAttributes;
    private int _sampleCount;
    private int _seedRun;
    private int _inFlight;

    public OpenTelemetryLabService(
        AppActivitySource activitySource,
        IMeterFactory meterFactory,
        IHostEnvironment environment,
        ILogger<OpenTelemetryLabService> logger)
    {
        _activitySource = activitySource;
        _logger = logger;

        var meter = meterFactory.Create(TelemetryConstants.MeterName);
        _requestCounter = meter.CreateCounter<long>(
            "otel_demo_requests_total",
            unit: "{request}",
            description: "Requests generated by the OpenTelemetry learning lab");
        _durationHistogram = meter.CreateHistogram<double>(
            "otel_demo_duration_ms",
            unit: "ms",
            description: "Duration of seeded OpenTelemetry learning-lab operations");
        meter.CreateObservableGauge(
            "otel_demo_in_flight",
            () => Volatile.Read(ref _inFlight),
            unit: "{request}",
            description: "OpenTelemetry learning-lab operations currently in flight");

        _resourceAttributes =
        [
            new("service.name", TelemetryConstants.ServiceName, "Configured by ResourceBuilder.AddService"),
            new("service.version", Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "1.0.0", "Application assembly version"),
            new("service.instance.id", $"{Environment.MachineName}-{Environment.ProcessId}", "Unique running process"),
            new("deployment.environment.name", environment.EnvironmentName, "Hosting environment")
        ];
    }

    public OpenTelemetrySeedResult Seed(int requestedCount)
    {
        int count = Math.Clamp(requestedCount, 1, 500);
        int run = Interlocked.Increment(ref _seedRun);
        var random = new Random(20260927 + run);
        var now = DateTimeOffset.UtcNow;
        string? firstTraceId = null;

        for (int index = 0; index < count; index++)
        {
            string operation = Operations[(index + run) % Operations.Length];
            string method = Methods[(index + run) % Methods.Length];
            bool failed = (index + run) % 9 == 0;
            double duration = CreateDuration(random, failed);
            var observedAt = now.AddSeconds(-random.Next(0, 30 * 60));
            string status = failed ? "Error" : "Ok";

            Interlocked.Increment(ref _inFlight);
            try
            {
                var rootTags = new ActivityTagsCollection
                {
                    { "demo.seed", true },
                    { "demo.operation", operation },
                    { "http.request.method", method },
                    { "url.path", $"/demo/{operation}" },
                    { "server.address", "monitoring-demo" },
                    { "http.response.status_code", failed ? 500 : 200 }
                };

                using var root = _activitySource.Source.StartActivity(
                    $"{method} /demo/{operation}",
                    ActivityKind.Server,
                    default(ActivityContext),
                    rootTags);
                firstTraceId ??= root?.TraceId.ToString();

                using (var child = _activitySource.Source.StartActivity(
                    $"{operation}.process",
                    ActivityKind.Internal,
                    Activity.Current?.Context ?? default,
                    new ActivityTagsCollection
                    {
                        { "demo.instrumentation", "manual" },
                        { "code.function.name", "OpenTelemetryLabService.Seed" }
                    }))
                {
                    child?.AddEvent(new ActivityEvent(
                        "demo.processing.completed",
                        tags: new ActivityTagsCollection { { "demo.duration_ms", duration } }));
                    child?.SetStatus(failed ? ActivityStatusCode.Error : ActivityStatusCode.Ok);
                }

                root?.SetStatus(
                    failed ? ActivityStatusCode.Error : ActivityStatusCode.Ok,
                    failed ? "Seeded demonstration failure" : null);

                var tags = new TagList
                {
                    { "demo.operation", operation },
                    { "http.request.method", method }
                };
                if (failed) tags.Add("error.type", "seeded_failure");
                _requestCounter.Add(1, tags);
                _durationHistogram.Record(duration, tags);

                if (failed)
                {
                    _logger.LogWarning(
                        "OpenTelemetry seed operation {Operation} failed after {DurationMilliseconds} ms in run {SeedRun}",
                        operation,
                        duration,
                        run);
                }
                else
                {
                    _logger.LogInformation(
                        "OpenTelemetry seed operation {Operation} completed in {DurationMilliseconds} ms in run {SeedRun}",
                        operation,
                        duration,
                        run);
                }

                AddSample(new OpenTelemetrySample(observedAt, operation, status, duration, 2, 2, 1));
            }
            finally
            {
                Interlocked.Decrement(ref _inFlight);
            }
        }

        return new OpenTelemetrySeedResult(count, run, firstTraceId, GetAnalytics(60));
    }

    public OpenTelemetryOverview GetOverview(int requestedWindowMinutes)
    {
        int windowMinutes = Math.Clamp(requestedWindowMinutes, 5, 240);
        return new OpenTelemetryOverview(
            DateTimeOffset.UtcNow,
            windowMinutes,
            GetAnalytics(windowMinutes),
            Architecture,
            ApiAndSdk,
            Instrumentation,
            _resourceAttributes,
            SemanticConventions,
            SignalComponents,
            Propagators);
    }

    private OpenTelemetryAnalytics GetAnalytics(int windowMinutes)
    {
        var cutoff = DateTimeOffset.UtcNow.AddMinutes(-windowMinutes);
        var samples = _samples
            .Where(sample => sample.Timestamp >= cutoff)
            .OrderBy(sample => sample.Timestamp)
            .ToArray();
        var durations = samples.Select(sample => sample.DurationMilliseconds).Order().ToArray();
        var timeline = samples
            .GroupBy(sample => new DateTimeOffset(
                sample.Timestamp.Year,
                sample.Timestamp.Month,
                sample.Timestamp.Day,
                sample.Timestamp.Hour,
                sample.Timestamp.Minute,
                0,
                TimeSpan.Zero))
            .Select(group => new OpenTelemetryTimelinePoint(
                group.Key,
                group.Sum(item => item.SpanCount),
                group.Sum(item => item.MetricPointCount),
                group.Sum(item => item.LogRecordCount),
                group.Count(item => item.Status == "Error")))
            .ToArray();
        var operations = samples
            .GroupBy(sample => sample.Operation)
            .OrderBy(group => group.Key)
            .Select(group => new OpenTelemetryOperationAnalytics(
                group.Key,
                group.Count(),
                group.Count(item => item.Status == "Error"),
                Math.Round(group.Average(item => item.DurationMilliseconds), 2)))
            .ToArray();

        return new OpenTelemetryAnalytics(
            samples.Length,
            samples.Sum(sample => sample.SpanCount),
            samples.Sum(sample => sample.MetricPointCount),
            samples.Sum(sample => sample.LogRecordCount),
            samples.Count(sample => sample.Status == "Error"),
            durations.Length == 0 ? 0 : Math.Round(durations.Average(), 2),
            Percentile(durations, 0.95),
            timeline,
            operations);
    }

    private void AddSample(OpenTelemetrySample sample)
    {
        _samples.Enqueue(sample);
        int count = Interlocked.Increment(ref _sampleCount);
        while (count > MaximumSamples && _samples.TryDequeue(out _))
        {
            count = Interlocked.Decrement(ref _sampleCount);
        }
    }

    private static double CreateDuration(Random random, bool failed) =>
        failed ? random.Next(650, 1_800) : random.Next(35, 620);

    private static double Percentile(double[] values, double percentile)
    {
        if (values.Length == 0) return 0;
        int index = (int)Math.Ceiling(values.Length * percentile) - 1;
        return Math.Round(values[Math.Clamp(index, 0, values.Length - 1)], 2);
    }

    private static readonly IReadOnlyList<OpenTelemetryArchitectureStage> Architecture =
    [
        new("Application", "API", "Instrumentation calls signal APIs without depending on an exporter."),
        new("Instrumentation", "Automatic + manual", "Libraries create telemetry and attach semantic attributes."),
        new("OpenTelemetry SDK", "Providers + processors", "The SDK samples, batches, aggregates, and owns export pipelines."),
        new("OTLP / Prometheus", "Export", "OTLP pushes logs and traces; Prometheus scrapes metrics."),
        new("Backends", "Analyze", "Tempo, Loki, Prometheus, Grafana, and Aspire store or visualize signals.")
    ];

    private static readonly IReadOnlyList<OpenTelemetryConceptItem> ApiAndSdk =
    [
        new("API", "Stable instrumentation surface", "ActivitySource, Meter, ILogger", "Application and library code creates telemetry here."),
        new("SDK", "Configurable implementation", "TracerProvider, MeterProvider, LoggerProvider", "The host configures sampling, processing, resources, readers, and exporters.")
    ];

    private static readonly IReadOnlyList<OpenTelemetryInstrumentationItem> Instrumentation =
    [
        new("Automatic", "ASP.NET Core", "Incoming HTTP spans and request duration metrics", true),
        new("Automatic", "HttpClient", "Outgoing HTTP client spans and metrics", true),
        new("Automatic", ".NET runtime", "GC, heap, thread-pool, and process metrics", true),
        new("Manual", TelemetryConstants.ActivitySourceName, "Business spans, attributes, events, and status", true),
        new("Manual", TelemetryConstants.MeterName, "Counters, histograms, and observable gauges", true),
        new("Manual", "Microsoft.Extensions.Logging", "Structured logs correlated to the active trace", true)
    ];

    private static readonly IReadOnlyList<OpenTelemetryConceptItem> SemanticConventions =
    [
        new("HTTP", "http.request.method", "GET | POST | PUT", "Standard attribute for the request method."),
        new("URL", "url.path", "/demo/checkout", "Standard low-cardinality request path."),
        new("Server", "server.address", "monitoring-demo", "Logical server host handling the request."),
        new("Response", "http.response.status_code", "200 | 500", "Standard numeric HTTP response status."),
        new("Custom", "demo.operation", "checkout | catalog | payment | fulfillment", "Namespaced, bounded domain-specific attribute.")
    ];

    private static readonly IReadOnlyList<OpenTelemetrySignalComponent> SignalComponents =
    [
        new("Tracer", "ActivitySource", "Spans", "Tempo + Aspire", "Records causal operations, timing, attributes, events, and status."),
        new("Meter", "System.Diagnostics.Metrics.Meter", "Metric points", "Prometheus + Aspire", "Records aggregatable counters, histograms, and observable gauges."),
        new("Logger", "Microsoft.Extensions.Logging", "Log records", "Loki or Aspire", "Records structured events with active trace and span correlation.")
    ];

    private static readonly IReadOnlyList<OpenTelemetryPropagatorItem> Propagators =
    [
        new("W3C Trace Context", "traceparent", "Carries trace ID, parent span ID, and sampling flags.", true),
        new("W3C Trace Context", "tracestate", "Carries ordered vendor-specific trace state.", true),
        new("W3C Baggage", "baggage", "Carries selected application context separately from span attributes.", true)
    ];
}

public sealed class OpenTelemetrySeedService : BackgroundService
{
    private readonly OpenTelemetryLabService _lab;

    public OpenTelemetrySeedService(OpenTelemetryLabService lab) => _lab = lab;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        try
        {
            await Task.Delay(TimeSpan.FromSeconds(4), stoppingToken);
            _lab.Seed(80);
        }
        catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
        {
            // Normal shutdown before the teaching dataset is created.
        }
    }
}

public sealed record OpenTelemetryOverview(
    DateTimeOffset GeneratedAt,
    int WindowMinutes,
    OpenTelemetryAnalytics Analytics,
    IReadOnlyList<OpenTelemetryArchitectureStage> Architecture,
    IReadOnlyList<OpenTelemetryConceptItem> ApiAndSdk,
    IReadOnlyList<OpenTelemetryInstrumentationItem> Instrumentation,
    IReadOnlyList<TelemetryResourceAttribute> Resource,
    IReadOnlyList<OpenTelemetryConceptItem> SemanticConventions,
    IReadOnlyList<OpenTelemetrySignalComponent> Signals,
    IReadOnlyList<OpenTelemetryPropagatorItem> Propagators);

public sealed record OpenTelemetryAnalytics(
    int OperationCount,
    int SpanCount,
    int MetricPointCount,
    int LogRecordCount,
    int ErrorCount,
    double AverageDurationMilliseconds,
    double P95DurationMilliseconds,
    IReadOnlyList<OpenTelemetryTimelinePoint> Timeline,
    IReadOnlyList<OpenTelemetryOperationAnalytics> Operations);

public sealed record OpenTelemetrySeedResult(
    int Seeded,
    int Run,
    string? FirstTraceId,
    OpenTelemetryAnalytics Analytics);

public sealed record OpenTelemetryTimelinePoint(DateTimeOffset Timestamp, int Spans, int Metrics, int Logs, int Errors);
public sealed record OpenTelemetryOperationAnalytics(string Operation, int Count, int ErrorCount, double AverageDurationMilliseconds);
public sealed record OpenTelemetryArchitectureStage(string Name, string Role, string Description);
public sealed record OpenTelemetryConceptItem(string Name, string Role, string Example, string Description);
public sealed record OpenTelemetryInstrumentationItem(string Type, string Library, string Produces, bool Enabled);
public sealed record TelemetryResourceAttribute(string Key, string Value, string Source);
public sealed record OpenTelemetrySignalComponent(string Name, string Api, string Output, string ExportedTo, string Description);
public sealed record OpenTelemetryPropagatorItem(string Name, string Field, string Purpose, bool Enabled);
internal sealed record OpenTelemetrySample(
    DateTimeOffset Timestamp,
    string Operation,
    string Status,
    double DurationMilliseconds,
    int SpanCount,
    int MetricPointCount,
    int LogRecordCount);
