using System.Collections.Concurrent;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using MonitoringDemo.ApiService.Telemetry;

namespace MonitoringDemo.ApiService.Services;

public sealed class OtlpLabService
{
    private const int MaximumSamples = 5_000;
    private static readonly string[] Operations = ["checkout", "catalog", "payment", "fulfillment"];
    private static readonly string[] Signals = ["Traces", "Metrics", "Logs"];

    private readonly AppActivitySource _activitySource;
    private readonly IConfiguration _configuration;
    private readonly ILogger<OtlpLabService> _logger;
    private readonly Counter<long> _batchCounter;
    private readonly Counter<long> _recordCounter;
    private readonly Counter<long> _wireBytesCounter;
    private readonly Histogram<double> _exportDuration;
    private readonly ConcurrentQueue<OtlpBatchSample> _samples = new();
    private int _sampleCount;
    private int _seedRun;
    private int _inFlight;

    public OtlpLabService(
        AppActivitySource activitySource,
        IMeterFactory meterFactory,
        IConfiguration configuration,
        ILogger<OtlpLabService> logger)
    {
        _activitySource = activitySource;
        _configuration = configuration;
        _logger = logger;

        var meter = meterFactory.Create(TelemetryConstants.MeterName);
        _batchCounter = meter.CreateCounter<long>(
            "otlp_demo_export_batches_total",
            unit: "{batch}",
            description: "OTLP export batches generated by the transport learning lab");
        _recordCounter = meter.CreateCounter<long>(
            "otlp_demo_export_records_total",
            unit: "{record}",
            description: "Telemetry records represented by OTLP learning-lab batches");
        _wireBytesCounter = meter.CreateCounter<long>(
            "otlp_demo_export_wire_bytes_total",
            unit: "By",
            description: "Modeled compressed payload bytes represented by OTLP learning-lab batches");
        _exportDuration = meter.CreateHistogram<double>(
            "otlp_demo_export_duration_ms",
            unit: "ms",
            description: "Modeled OTLP export request duration");
        meter.CreateObservableGauge(
            "otlp_demo_exports_in_flight",
            () => Volatile.Read(ref _inFlight),
            unit: "{export}",
            description: "OTLP learning-lab exports currently in flight");
    }

    public OtlpSeedResult Seed(int requestedCount)
    {
        int count = Math.Clamp(requestedCount, 1, 500);
        int run = Interlocked.Increment(ref _seedRun);
        var random = new Random(4317 + (run * 4318));
        var now = DateTimeOffset.UtcNow;

        for (int index = 0; index < count; index++)
        {
            string protocol = index % 2 == 0 ? "gRPC" : "HTTP/protobuf";
            string signal = Signals[(index + run) % Signals.Length];
            string operation = Operations[(index + run) % Operations.Length];
            string destination = protocol == "gRPC"
                ? "Aspire Dashboard"
                : signal == "Logs" ? "Loki" : signal == "Traces" ? "Tempo" : "OTLP collector";
            int recordCount = random.Next(8, 65);
            int rawBytes = recordCount * random.Next(170, 390);
            int wireBytes = (int)Math.Round(rawBytes * (protocol == "gRPC" ? 0.56 : 0.64));
            double duration = Math.Round(protocol == "gRPC" ? random.NextDouble() * 28 + 4 : random.NextDouble() * 46 + 8, 2);
            bool retried = index > 0 && (index + run) % 17 == 0;
            bool failed = index > 0 && (index + run) % 43 == 0;
            string status = failed ? "Failed" : retried ? "Retried" : "Exported";
            int attempts = retried || failed ? 2 : 1;
            var observedAt = now.AddSeconds(-random.Next(0, 30 * 60));
            string batchId = $"otlp-{run:D3}-{index + 1:D3}";

            Interlocked.Increment(ref _inFlight);
            try
            {
                EmitTelemetry(batchId, protocol, signal, operation, recordCount, rawBytes, wireBytes, duration, status);
                AddSample(new OtlpBatchSample(
                    batchId,
                    observedAt,
                    protocol,
                    signal,
                    destination,
                    operation,
                    recordCount,
                    rawBytes,
                    wireBytes,
                    duration,
                    status,
                    attempts));
            }
            finally
            {
                Interlocked.Decrement(ref _inFlight);
            }
        }

        return new OtlpSeedResult(count, run, GetAnalytics(60));
    }

    public OtlpOverview GetOverview(int requestedWindowMinutes)
    {
        int windowMinutes = Math.Clamp(requestedWindowMinutes, 5, 240);
        return new OtlpOverview(
            DateTimeOffset.UtcNow,
            windowMinutes,
            GetAnalytics(windowMinutes),
            Protocols,
            BuildEndpoints(),
            EndpointPrecedence);
    }

    private void EmitTelemetry(
        string batchId,
        string protocol,
        string signal,
        string operation,
        int recordCount,
        int rawBytes,
        int wireBytes,
        double duration,
        string status)
    {
        var tags = new TagList
        {
            { "otlp.protocol", protocol },
            { "otel.signal", signal.ToLowerInvariant() },
            { "demo.operation", operation },
            { "exporter.status", status.ToLowerInvariant() }
        };
        _batchCounter.Add(1, tags);
        _recordCounter.Add(recordCount, tags);
        _wireBytesCounter.Add(wireBytes, tags);
        _exportDuration.Record(duration, tags);

        if (signal == "Traces")
        {
            using var activity = _activitySource.Source.StartActivity(
                $"OTLP export {operation}",
                ActivityKind.Producer,
                default(ActivityContext),
                new ActivityTagsCollection
                {
                    { "demo.otlp", true },
                    { "demo.batch.id", batchId },
                    { "otlp.protocol", protocol },
                    { "otel.signal", "traces" },
                    { "demo.record_count", recordCount },
                    { "demo.payload.raw_bytes", rawBytes },
                    { "demo.payload.wire_bytes", wireBytes }
                });
            activity?.AddEvent(new ActivityEvent("otlp.batch.exported"));
            activity?.SetStatus(status == "Failed" ? ActivityStatusCode.Error : ActivityStatusCode.Ok);
        }

        if (status == "Failed")
        {
            _logger.LogWarning(
                "OTLP batch {BatchId} for {Signal} failed over {Protocol} after {DurationMilliseconds} ms",
                batchId, signal, protocol, duration);
        }
        else
        {
            _logger.LogInformation(
                "OTLP batch {BatchId} exported {RecordCount} {Signal} records over {Protocol} in {DurationMilliseconds} ms",
                batchId, recordCount, signal, protocol, duration);
        }
    }

    private OtlpAnalytics GetAnalytics(int windowMinutes)
    {
        var cutoff = DateTimeOffset.UtcNow.AddMinutes(-windowMinutes);
        var samples = _samples
            .Where(sample => sample.Timestamp >= cutoff)
            .OrderBy(sample => sample.Timestamp)
            .ToArray();
        var durations = samples.Select(sample => sample.DurationMilliseconds).Order().ToArray();

        var timeline = samples
            .GroupBy(sample => new DateTimeOffset(
                sample.Timestamp.Year,
                sample.Timestamp.Month,
                sample.Timestamp.Day,
                sample.Timestamp.Hour,
                sample.Timestamp.Minute,
                0,
                TimeSpan.Zero))
            .Select(group => new OtlpTimelinePoint(
                group.Key,
                group.Count(item => item.Protocol == "gRPC"),
                group.Count(item => item.Protocol == "HTTP/protobuf"),
                group.Sum(item => item.RecordCount),
                group.Count(item => item.Status == "Failed")))
            .ToArray();

        var protocols = samples
            .GroupBy(sample => sample.Protocol)
            .OrderBy(group => group.Key)
            .Select(group => new OtlpProtocolAnalytics(
                group.Key,
                group.Count(),
                group.Sum(item => item.RecordCount),
                group.Count(item => item.Status == "Retried"),
                group.Count(item => item.Status == "Failed"),
                Math.Round(group.Average(item => item.DurationMilliseconds), 2),
                Percentile(group.Select(item => item.DurationMilliseconds).Order().ToArray(), 0.95),
                group.Sum(item => item.WireBytes)))
            .ToArray();

        var signals = samples
            .GroupBy(sample => sample.Signal)
            .OrderBy(group => group.Key)
            .Select(group => new OtlpSignalAnalytics(
                group.Key,
                group.Count(),
                group.Sum(item => item.RecordCount),
                group.Sum(item => item.WireBytes),
                group.Count(item => item.Status == "Failed")))
            .ToArray();

        var recentBatches = samples
            .OrderByDescending(sample => sample.Timestamp)
            .Take(12)
            .Select(sample => new OtlpBatch(
                sample.BatchId,
                sample.Timestamp,
                sample.Protocol,
                sample.Signal,
                sample.Destination,
                sample.RecordCount,
                sample.WireBytes,
                sample.DurationMilliseconds,
                sample.Status,
                sample.Attempts))
            .ToArray();

        int rawBytes = samples.Sum(sample => sample.RawBytes);
        int wireBytes = samples.Sum(sample => sample.WireBytes);
        return new OtlpAnalytics(
            samples.Length,
            samples.Sum(sample => sample.RecordCount),
            samples.Count(sample => sample.Status == "Retried"),
            samples.Count(sample => sample.Status == "Failed"),
            wireBytes,
            rawBytes == 0 ? 0 : Math.Round((1 - (double)wireBytes / rawBytes) * 100, 1),
            durations.Length == 0 ? 0 : Math.Round(durations.Average(), 2),
            Percentile(durations, 0.95),
            timeline,
            protocols,
            signals,
            recentBatches);
    }

    private IReadOnlyList<OtlpEndpointConfiguration> BuildEndpoints()
    {
        string? genericEndpoint = _configuration["OTEL_EXPORTER_OTLP_ENDPOINT"];
        string genericProtocol = NormalizeProtocol(_configuration["OTEL_EXPORTER_OTLP_PROTOCOL"]);
        string? tracesEndpoint = _configuration["OTEL_EXPORTER_OTLP_TRACES_ENDPOINT"];
        string tracesProtocol = NormalizeProtocol(_configuration["OTEL_EXPORTER_OTLP_TRACES_PROTOCOL"] ?? genericProtocol);
        string? metricsEndpoint = _configuration["OTEL_EXPORTER_OTLP_METRICS_ENDPOINT"];
        string metricsProtocol = NormalizeProtocol(_configuration["OTEL_EXPORTER_OTLP_METRICS_PROTOCOL"] ?? genericProtocol);
        string? logsEndpoint = _configuration["OTEL_EXPORTER_OTLP_LOGS_ENDPOINT"];
        string logsProtocol = NormalizeProtocol(_configuration["OTEL_EXPORTER_OTLP_LOGS_PROTOCOL"] ?? genericProtocol);

        return
        [
            Endpoint("Aspire / generic", "All signals", genericProtocol, genericEndpoint, "OTEL_EXPORTER_OTLP_ENDPOINT", "The SDK resolves signal-specific variables before this shared fallback."),
            Endpoint("Signal override", "Traces", tracesProtocol, tracesEndpoint, "OTEL_EXPORTER_OTLP_TRACES_ENDPOINT", "Overrides the generic trace destination when set."),
            Endpoint("Signal override", "Metrics", metricsProtocol, metricsEndpoint, "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT", "Overrides the generic metric destination when set."),
            Endpoint("Signal override", "Logs", logsProtocol, logsEndpoint, "OTEL_EXPORTER_OTLP_LOGS_ENDPOINT", "Overrides the generic log destination when set."),
            Endpoint("Tempo", "Traces", "HTTP/protobuf", _configuration["TEMPO_OTLP_ENDPOINT"], "TEMPO_OTLP_ENDPOINT", "Named exporter configured by this demo for trace storage."),
            Endpoint("Loki", "Logs", "HTTP/protobuf", _configuration["LOKI_OTLP_ENDPOINT"], "LOKI_OTLP_ENDPOINT", "Named exporter configured by this demo for structured log storage.")
        ];
    }

    private static OtlpEndpointConfiguration Endpoint(
        string destination,
        string signals,
        string protocol,
        string? endpoint,
        string source,
        string note) =>
        new(destination, signals, protocol, SanitizeEndpoint(endpoint), source, !string.IsNullOrWhiteSpace(endpoint), note);

    private static string SanitizeEndpoint(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return "Not configured";
        if (!Uri.TryCreate(value, UriKind.Absolute, out var endpoint)) return "Configured (value is not a valid absolute URI)";
        var builder = new UriBuilder(endpoint) { UserName = string.Empty, Password = string.Empty, Query = string.Empty };
        return builder.Uri.GetLeftPart(UriPartial.Path).TrimEnd('/');
    }

    private static string NormalizeProtocol(string? value) =>
        value?.Trim().ToLowerInvariant() switch
        {
            "http/protobuf" => "HTTP/protobuf",
            "grpc" => "gRPC",
            _ => "gRPC"
        };

    private void AddSample(OtlpBatchSample sample)
    {
        _samples.Enqueue(sample);
        int count = Interlocked.Increment(ref _sampleCount);
        while (count > MaximumSamples && _samples.TryDequeue(out _))
        {
            count = Interlocked.Decrement(ref _sampleCount);
        }
    }

    private static double Percentile(double[] values, double percentile)
    {
        if (values.Length == 0) return 0;
        int index = (int)Math.Ceiling(values.Length * percentile) - 1;
        return Math.Round(values[Math.Clamp(index, 0, values.Length - 1)], 2);
    }

    private static readonly IReadOnlyList<OtlpProtocolDefinition> Protocols =
    [
        new(
            "OTLP/gRPC",
            "gRPC",
            4317,
            "HTTP/2 + Protocol Buffers",
            "Long-lived multiplexed channels with unary Export RPCs.",
            ["opentelemetry.proto.collector.trace.v1.TraceService/Export", "opentelemetry.proto.collector.metrics.v1.MetricsService/Export", "opentelemetry.proto.collector.logs.v1.LogsService/Export"],
            ["Efficient binary framing", "HTTP/2 multiplexing", "Native deadlines and status codes"]),
        new(
            "OTLP/HTTP",
            "HTTP/protobuf",
            4318,
            "HTTP POST + Protocol Buffers",
            "Independent HTTP requests use stable signal-specific paths.",
            ["/v1/traces", "/v1/metrics", "/v1/logs"],
            ["Proxy and firewall friendly", "Simple endpoint inspection", "Optional JSON encoding by compatible receivers"])
    ];

    private static readonly IReadOnlyList<OtlpEndpointRule> EndpointPrecedence =
    [
        new(1, "Signal-specific endpoint", "OTEL_EXPORTER_OTLP_<SIGNAL>_ENDPOINT", "Highest priority; used only by that signal."),
        new(2, "Generic endpoint", "OTEL_EXPORTER_OTLP_ENDPOINT", "Shared base endpoint when no signal override exists."),
        new(3, "SDK default", "http://localhost:4317", "Used when the application and environment do not configure an endpoint."),
        new(4, "Protocol and headers", "OTEL_EXPORTER_OTLP_*_PROTOCOL / *_HEADERS", "Resolved per signal using the same override pattern; header values must remain secret.")
    ];
}

public sealed class OtlpSeedService : BackgroundService
{
    private readonly OtlpLabService _lab;

    public OtlpSeedService(OtlpLabService lab) => _lab = lab;

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        try
        {
            await Task.Delay(TimeSpan.FromSeconds(5), stoppingToken);
            _lab.Seed(120);
        }
        catch (OperationCanceledException) when (stoppingToken.IsCancellationRequested)
        {
            // Normal shutdown before the teaching dataset is created.
        }
    }
}

public sealed record OtlpOverview(
    DateTimeOffset GeneratedAt,
    int WindowMinutes,
    OtlpAnalytics Analytics,
    IReadOnlyList<OtlpProtocolDefinition> Protocols,
    IReadOnlyList<OtlpEndpointConfiguration> Endpoints,
    IReadOnlyList<OtlpEndpointRule> EndpointPrecedence);

public sealed record OtlpAnalytics(
    int BatchCount,
    int RecordCount,
    int RetriedBatchCount,
    int FailedBatchCount,
    int WireBytes,
    double CompressionSavingsPercent,
    double AverageDurationMilliseconds,
    double P95DurationMilliseconds,
    IReadOnlyList<OtlpTimelinePoint> Timeline,
    IReadOnlyList<OtlpProtocolAnalytics> Protocols,
    IReadOnlyList<OtlpSignalAnalytics> Signals,
    IReadOnlyList<OtlpBatch> RecentBatches);

public sealed record OtlpSeedResult(int Seeded, int Run, OtlpAnalytics Analytics);
public sealed record OtlpTimelinePoint(DateTimeOffset Timestamp, int GrpcBatches, int HttpBatches, int Records, int Failures);
public sealed record OtlpProtocolAnalytics(string Protocol, int BatchCount, int RecordCount, int RetriedBatchCount, int FailedBatchCount, double AverageDurationMilliseconds, double P95DurationMilliseconds, int WireBytes);
public sealed record OtlpSignalAnalytics(string Signal, int BatchCount, int RecordCount, int WireBytes, int FailedBatchCount);
public sealed record OtlpBatch(string BatchId, DateTimeOffset Timestamp, string Protocol, string Signal, string Destination, int RecordCount, int WireBytes, double DurationMilliseconds, string Status, int Attempts);
public sealed record OtlpProtocolDefinition(string Name, string Protocol, int DefaultPort, string Transport, string Description, IReadOnlyList<string> MethodsOrPaths, IReadOnlyList<string> Strengths);
public sealed record OtlpEndpointConfiguration(string Destination, string Signals, string Protocol, string Endpoint, string Source, bool Configured, string Note);
public sealed record OtlpEndpointRule(int Priority, string Name, string Variable, string Description);

internal sealed record OtlpBatchSample(
    string BatchId,
    DateTimeOffset Timestamp,
    string Protocol,
    string Signal,
    string Destination,
    string Operation,
    int RecordCount,
    int RawBytes,
    int WireBytes,
    double DurationMilliseconds,
    string Status,
    int Attempts);
