receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
    spike_limit_mib: 64
  batch:
    timeout: 1s
    send_batch_size: 512
    send_batch_max_size: 1024

exporters:
  debug:
    verbosity: basic
  otlp_http/tempo:
    endpoint: ${env:TEMPO_OTLP_HTTP_ENDPOINT}
  otlp_http/loki:
    logs_endpoint: ${env:LOKI_OTLP_HTTP_LOGS_ENDPOINT}
  prometheus:
    endpoint: 0.0.0.0:9464
    namespace: monitoring_demo_collector

service:
  telemetry:
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp_http/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp_http/loki, debug]
