apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: $PROMETHEUS_DATASOURCE_URL
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    editable: false
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: $LOKI_DATASOURCE_URL
    jsonData:
      maxLines: 1000
    editable: false
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: $TEMPO_DATASOURCE_URL
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -2m
        spanEndTimeShift: 2m
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: true
        filterBySpanID: true
      nodeGraph:
        enabled: true
    editable: false
